name = "Proactive"
license = "MIT"
licenselink = "https://github.com/yourname/yourtheme/blob/master/LICENSE.md"
description = ""
homepage = "http://example.com/"
tags = []
features = []
min_version = "0.31.1"

[author]
  name = "nicolas narbais"
  homepage = "https://github.com/fr3nchN/"
